import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
 fertigungSidebar: [
        'fertigung/intro',
            {
                type: 'category',
                label: 'Rückmeldung',
                link: {
                    type: 'generated-index',
                },
                items: [
                    {
                        type: 'autogenerated',
                        dirName: 'fertigung/areas/rueckmeldung'
                    },
                ]
            },
            {
                type: 'category',
                label: 'Werkzeug & Messmittelausschreibung',
                items: [
                    {
                    type: 'autogenerated',
                    dirName: 'fertigung/areas/werkzeug'
                    },
                ]
            },
            {
                type: 'category',
                label: 'Reporting',
                link: {
                    type: 'generated-index',
            },
            items: [
                {
                type: 'autogenerated',
                dirName: 'fertigung/areas/reporting'
                },
            ]
            },
            {
                type: 'category',
                label: 'Digitale Messwerterfassung',
                link: {
                    type: 'generated-index',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'fertigung/areas/digitale-messwerterfassung'
                },
            ]
            },
            {
                type: 'category',
                label: 'Härteprüfung',
                link: {
                    type: 'generated-index',
                    description: `Die Härteprüfung gibt es einmal aus Sicht der Härterei, welche den richtigen Umgang mit der Anwendung beschreibt und
                                    einmal aus Sicht des Channels, wann und wie die gehärteten Ringe abgefasst werden können.`,
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'fertigung/areas/haertepruefung'
                },
            ]
            },
            'fertigung/areas/sls',
            'fertigung/areas/suche'
    ],
    feinplanungSidebar: [
        'feinplanung/intro',
        {
            type: 'category',
            label: 'Sequenz',
            link: {
                type: 'generated-index',
            },
            items: [
                {
                type: 'autogenerated',
                dirName: 'feinplanung/sequenz'
                }, 
            ]
        },
        'feinplanung/übersicht',
        'feinplanung/logbuch',
        'feinplanung/vorschau',
        'feinplanung/plugins',       
        'feinplanung/schichtplanung',               
    ],
    wkzmmSidebar: [
        {
            type: 'category',
            label: 'Werkzeug & Messmittel',
            items: ['werkzeug-messmittel/coming-soon'],
        },
    ],
    pprSidebar: [
        'ppr/allgemein',
        'ppr/dokumente-drucken',
        'ppr/auftragsbegleitkarte',
        'ppr/auslagerungsprotokoll',
        'ppr/pruefbegleitkarte',
        'ppr/maschinenfreigabekarte',
        'ppr/montagefreigabekarte',
        'ppr/zvp_schein',
        'ppr/schneidbeleg',
        'ppr/walzbeleg',
        'ppr/montagebegleitkarte',
        'ppr/pvsequenz',
        'ppr/pvbegleitkarte',
        'ppr/rohmaterialabfassung',
        'ppr/liste-aller-dokumente'
    ],
    newsSidebar: [
        'news/aktuelles'
    ],
};

export default sidebars;
